# This is a config for E2B sandbox template.
# You can use template ID (g0njjkn8q6l0dzmarnq9) or template name (vibe-coding-app-frankz) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-coding-app-frankz") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-coding-app-frankz") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-coding-app-frankz')

team_id = "fab67523-dab2-469a-b1da-7ee1bd1d6375"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-coding-app-frankz"
template_id = "g0njjkn8q6l0dzmarnq9"
